services:
  reverse-proxy:
    image: traefik:v3.3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Setup Let's Encrypt certificates for HTTPS
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=cmnemoi@askneron.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Redirect HTTP to HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - emush_rag

  app:
    image: cmnemoi/emush_rag_api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`askneron.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    ports:
    - mode: ingress
      target: 8080
      protocol: tcp
    env_file:
      - .env
    depends_on:
      - vector_store
      - jaeger
    networks:
      - emush_rag
    extra_hosts:
      - "host.docker.internal:host-gateway"

  vector_store:
    image: chromadb/chroma:1.0.15
    ports:
    - mode: ingress
      target: 8000
      protocol: tcp
    volumes:
    - ./chroma:/data
    restart: unless-stopped
    networks:
      - emush_rag

  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    ports:
    - mode: ingress
      target: 4317
      protocol: tcp
    - mode: ingress
      target: 4318
      protocol: tcp
    - mode: ingress
      target: 9411
      protocol: tcp
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - emush_rag
    restart: unless-stopped

  grafana:
    image: cmnemoi/emush_rag_grafana:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.askneron.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    ports:
    - mode: ingress
      target: 3000
      protocol: tcp
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env
    depends_on:
      - jaeger
    networks:
      - emush_rag
    restart: unless-stopped

networks:
  emush_rag:
    driver: overlay

volumes:
  letsencrypt:
  grafana-data: