version: "3.9"

services:
  reverse-proxy:
    image: traefik:v3.3.1
    command:
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      # HTTP / HTTPS entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      # Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=cmnemoi@askneron.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - emush_rag

  app:
    image: cmnemoi/emush_rag_api:latest
    env_file:
      - .env
    depends_on:
      - vector_store
      - jaeger
    networks:
      - emush_rag
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - mode: ingress
        target: 8080
        protocol: tcp
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=emush_rag"
        - "traefik.http.routers.app.rule=Host(`askneron.com`)"
        - "traefik.http.routers.app.entrypoints=websecure"
        - "traefik.http.routers.app.tls.certresolver=myresolver"
        - "traefik.http.services.app.loadbalancer.server.port=8080"
      restart_policy:
        condition: on-failure

  vector_store:
    image: chromadb/chroma:1.0.15
    volumes:
      - ./chroma:/data
    networks:
      - emush_rag
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 8000
        protocol: tcp

  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - emush_rag
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 4317
        protocol: tcp
      - mode: ingress
        target: 4318
        protocol: tcp
      - mode: ingress
        target: 9411
        protocol: tcp

  grafana:
    image: cmnemoi/emush_rag_grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env
    depends_on:
      - jaeger
    networks:
      - emush_rag
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 3000
        protocol: tcp
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=emush_rag"
        - "traefik.http.routers.grafana.rule=Host(`grafana.askneron.com`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=myresolver"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  emush_rag:
    driver: overlay

volumes:
  letsencrypt:
  grafana-data:
