services:
  app:
    image: cmnemoi/emush_rag_api:latest
    ports:
    - mode: ingress
      target: 3000
      published: 3000
      protocol: tcp
    env_file:
      - .env
    depends_on:
      - vector_store
    networks:
      - emush_rag
    extra_hosts:
      - "host.docker.internal:host-gateway"

  vector_store:
    image: chromadb/chroma:0.6.0
    ports:
    - mode: ingress
      target: 8000
      protocol: tcp
    volumes:
      - ./chroma:/chroma/chroma
    networks:
      - emush_rag

networks:
  emush_rag:
    driver: overlay
