services:
  app:
    image: cmnemoi/emush_rag_api:latest
    ports:
    - mode: ingress
      target: 8000
      published: 8000
      protocol: tcp
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
